# Generated by Django 5.1.6 on 2025-03-06 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginrecord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loginrecord',
            name='fullname',
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
