# Generated by Django 5.1.6 on 2025-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_remove_loginrecord_email_remove_loginrecord_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
