# Generated by Django 5.1.6 on 2025-03-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_loginrecord_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
