# Generated by Django 5.1.6 on 2025-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_loginrecord_email_loginrecord_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
