# Generated by Django 5.1.6 on 2026-06-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_blog_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='login_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
