# Generated by Django 5.1.6 on 2026-06-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_alter_loginrecord_login_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
